import './style.less';
import './images/pressure.svg';
import './images/clearly-night.svg';
import './images/clearly.svg';
import './images/cloudiness.svg';
import './images/drizzle.svg';
import './images/fog.svg';
import './images/freezing-rain.svg';
import './images/humidity.svg';
import './images/light-rain-night.svg';
import './images/light-rain.svg';
import './images/light-spotty-night.svg';
import './images/little-spotty.svg';
import './images/precipitation.svg';
import './images/rain.svg';
import './images/snow.svg';
import './images/sunrise.svg';
import './images/sunset.svg';
import './images/temperature.svg';
import './images/thunderstorm.svg';
import './images/wind.svg';
import './images/windy.svg';

const apiKey = process.env.API_KEY;